### ISSUE TITLE
Feature Request: Repair

### ISSUE THREAD

**Issue by RillSoji** [ADHDMC/SimplePlayerUtils#3]
I would love to see a /repair option to fully repair the item you are holding. And/or a /repairall to fully repair everything on your person or in your inventory. Thank you for considering!

**Comment by RhythmicSys** [comment]
I realize it has been over a year, but in case you still were wanting this, I separated this specific plugin into 2 separate plugins:

[AdminHax](https://github.com/Simplexity-Development/AdminHax/tree/master) - [Modrinth](https://modrinth.com/plugin/admin-hax)

And

[SimpleInventories](https://github.com/Simplexity-Development/SimpleInventories) - [Modrinth](https://modrinth.com/plugin/simpleinventories)

I was able to add the `/repair` command to AdminHax 👍🏻
